task: "nextqa_mc_test"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.nextqa_doc_to_visual
doc_to_text: !function utils.nextqa_doc_to_text_mc
doc_to_target: !function utils.nextqa_doc_to_target
generation_kwargs:
  max_new_tokens: 1
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.nextqa_mc_process_results
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
include: _default_template_yaml
