dataset_path: ./data/VideoEval-Pro
dataset_kwargs:
  token: True
  cache_dir: videopro
  video: True
  ignore_verifications: True
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
task: videopro_mcq
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videopro_doc_to_visual_mcq
doc_to_text: !function utils.videopro_doc_to_text_mcq
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.videopro_mcq_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: videopro_percetion_score
    aggregation: !function utils.vidoepro_mcq_aggregate_results
    higher_is_better: true